"""empty message

Revision ID: 091023cfcbfd
Revises: 782e7de4c58f
Create Date: 2022-12-09 23:12:29.416542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091023cfcbfd'
down_revision = '782e7de4c58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('hourly_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_rate', sa.FLOAT(), nullable=False))

    op.drop_table('wage')
    # ### end Alembic commands ###
